### ISSUE TITLE
Checklist for Temurin Releases 8u322, jdk-11.0.14, and jdk-17.0.2

### ISSUE THREAD

**Issue by sxa** [adoptium/adoptium#108]
**NOTE: Items marked `jdkxx` and `TEMPLATE_UPDATEME` should be replaced while deploying this issue template. It is recommended to delete this line once you've done so :-)**

This Temurin release checklist based on the [release doc](https://github.com/adoptium/temurin-build/blob/master/RELEASING.md) captures what activities must happen during a release.  

The target release date is: 21/1/2022 (Primary Platforms) 28/1/2022 (Other platforms, except AIX JDK17)

The release champion for this release is: Stewart Addison @sxa 

Planned absences during the release cycle: 
- @sxa from Wednesday Feb02 until Monday Feb07

The role of the release champion is to ensure that all release activities listed in this checklist get completed (by delegation to the broader team or by the release champion themselves).  The final task of the release champion during a release is to confirm that all items in the checklist were completed satisfactorily and the release can be declared complete.

Everyone participating in a release, including the release champion are requested to provide feedback into the [release retrospective](https://github.com/adoptium/adoptium/issues/104) so that the release process can be continuously improved (through simplification and/or automation).

-------

One Week Prior to Release:

- [x] **Release Champion named** whose responsibility is to ensure every item in this checklist gets completed
- [x] **Declare code freeze** to ensure stability of build systems and infrastructure during release process - chill requested - one change requested by Shelley
- [x] **Disable nightly testing** to free up resources and ensure no competing jobs during release week (Deferred til the day before release - sxa)
- [x] **Run a trial release pipeline** to ensure less surprises on release day (typically against a milestone build)

-------

Release Week Checklist:

- [x] **Add website banner** (_automate_* via github workflow in website repository) - Announce that we target releases to be available within 48-72 hours of the GA tags being available
- [x] **Check Tags have been released upstream** - Look for mailing list announcements and `-ga` tags in version control.
- [x] **Check Tags have been Mirrored** [Mirrors](https://ci.adoptopenjdk.net/view/git-mirrors/job/git-mirrors/job/adoptium/).
- [x] **Launch build pipelines** for each version being released [(as per release doc](https://github.com/adoptium/temurin-build/blob/master/RELEASING.md#steps-for-every-version)) once release tags are available via [launch page](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/build) in Jenkins.  Provide links in this issue to each version's pipeline build(s). There may be multiple pipelines per version if primary and secondary platforms are separated to expedite the release.  In some cases,  where there are unforeseen configuration or infrastructure issues, reruns may be needed.
  - jdk8 pipeline(s):
    - **primary jdk8 pipeline:** [8u322-b06](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/1941) (Currently "optimistic" against commit `236b800` as the `-ga` tag [has not been put in place to match it yet](https://mail.openjdk.java.net/pipermail/jdk8u-dev/2022-January/014506.html) but it keeps the machines in use)
      - rerun(s):
    - **secondary jdk8 pipeline:** [aarch32/arm32](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/1950)
      - reruns(s):
  - jdk11 pipeline(s):
    - **primary jdk11 pipeline:** [11.0.14+9](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/1795/console)
      - rerun(s):
    - **secondary jdk11 pipeline:** [11.0.14.1+1](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/1817/)
      - rerun(s):
  - jdk17 pipeline(s):
    - **primary jdk17 pipeline:** [jdk 17.0.2+8](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk17-pipeline/284)
      - rerun(s):
    - **secondary jdkxx pipeline:**
      - rerun(s):
- [x] **Add links to the [status doc](https://github.com/adoptium/adoptium/issues/TEMPLATE_UPDATEME)** to indicate per-platform builds ready
- [x] **Summarize test results**.  Find each launched build pipeline in [TRSS](https://trss.adoptium.net/) to view a summary of test results.  Can use the Release Summary Report feature in TRSS to generate a summary of failures, history and possible issues in markup format to be added to this issue as a comment.
- [x] **Triage** each build and test failure in the release summary report (following the [Triage guidelines](https://github.com/adoptium/aqa-tests/blob/master/doc/Triage.md)) and determine blocking or non-blocking.  Supply links to triage issues or docs for each version here.
  - jdk8 triage summary: https://github.com/adoptium/adoptium/issues/113
  - jdk11 triage summary: https://github.com/adoptium/adoptium/issues/112
  - jdk17 triage summary: https://github.com/adoptium/adoptium/issues/114
- [x] **Fix** blocking failures if they exist and confirm others are non-blocking.
- [x] **Confirm Temurin-compliance items completed**, per platform/version/binaryType
- [x] **Get PMC 'ready to publish' approval**, once no blocking failures exist.
- [x] **Publish the release** (run the restricted access [release tool job](https://ci.adoptopenjdk.net/job/build-scripts/job/release/job/refactor_openjdk_release_tool/) on Jenkins)
- [x] **Verify binaries published successfully** to github releases repo and website (_automate_*, this could also be an automated test)

- [x] **Publish updates to the containers to dockerhub** - ~~Initial set submitted at https://github.com/docker-library/official-images/pull/11773~~. JDK8/arm32 and JDK11.0.14.1 submitted at https://github.com/docker-library/official-images/pull/11845
- [x] **Edit the [Homebrew Temurin Cask](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/temurin.rb) and replace the version and sha256 as appropriate.  This means for Homebrew users that they install the latest by default and can use the `@` notation to install older versions if they wish. Done for [8u322](https://github.com/Homebrew/homebrew-cask-versions/pull/13126), [11.0.14](https://github.com/Homebrew/homebrew-cask-versions/pull/13111) and [17.0.2](https://github.com/Homebrew/homebrew-cask/pull/118301) and [11.0.14.1](https://github.com/Homebrew/homebrew-cask-versions/pull/13279)
- [x] **Update support page** (_automate_* github workflow to create a PR to update [support.handlebars](https://github.com/adoptium/adoptium.net/blob/master/src/handlebars/support.handlebars)) - [CREATED](https://github.com/adoptium/adoptium.net/pull/276) and again for [11.0.14.1](https://github.com/adoptium/adoptium.net/pull/281).
- [x] **Update release notes** (_automate_* - github workflow to create update for [release notes page](https://adoptium.net/release_notes.html)) [PR](https://github.com/adoptium/adoptium.net/pull/282)
- [x] **Trigger linux installers pipeline** currently it is part of the build pipelines (will eventually be updated to run independently) [PR for 11.0.14](https://github.com/adoptium/installer/pull/423) | [PR for 17.0.2](https://github.com/adoptium/installer/pull/425) | [PR for 11.0.14.1+1](https://github.com/adoptium/installer/pull/429) - [pipeline run1](https://ci.adoptopenjdk.net/job/adoptium-packages-linux-pipeline/82) - [PR for 8u322](https://github.com/adoptium/installer/pull/428) - [pipeline run](https://ci.adoptopenjdk.net/job/adoptium-packages-linux-pipeline/83/)
- [x] **Publicize the release** via Slack #release channel and Twitter (can be partially automated)
- [x] **Declare code freeze end** opening up the code for further development
- [x] **Remove website banner** (_automate_* via github workflow in website repository)
- [x] **Check for presence of jdk8u aarch32 GA tag and mirror it** [Mercurial repo](https://hg.openjdk.java.net/aarch32-port/jdk8u) - [Mirror job](https://ci.adoptopenjdk.net/view/git-mirrors/job/git-mirrors/job/adoptium/job/git-hg-aarch32-jdk8u/)
- [x] **Do all of the above for the jdk8u/aarch32 build**
- [x] **Declare the release complete** and close this issue

**Comment by karianna** [comment]
@sxa I assume this can be closed now if we treat Alpine as an excpetion?

**Comment by karianna** [comment]
> 

TCK testing Alpine can be challenging :-), we are still going to push it out

**Comment by sxa** [comment]
> @sxa I assume this can be closed now if we treat Alpine as an excpetion?

My preference is to keep it open since we're still aiming to ship it as a part of this release cycle.

**Comment by bodhi-one** [comment]
Curious what the naming rationale is here: from  11.0.14_9 to 11.0.14.1_1 (and not say 11.0.14_10) ?

**Comment by sxa** [comment]
It's a new "final" release outside the normal quarterly cycle so using a new number (which comes from the upstream OpenJDK project) avoids any confusion. It's rare for this to happen - I think it's only been done one other time in the last five years or so.

**Comment by sxa** [comment]
> Curious what the naming rationale is here: from 11.0.14_9 to 11.0.14.1_1 (and not say 11.0.14_10) ?

It's a new "final" release outside the normal quarterly cycle so using a new number (which comes from the upstream OpenJDK project) avoids any confusion. It's rare for this to happen - I think it's only been done one other time in the last five years or so.
