### ISSUE TITLE
Checklist for Temurin Release for jdk-18+36 (March 2022)

### ISSUE THREAD

**Issue by smlambert** [adoptium/adoptium#130]
This Temurin release checklist based on the [release doc](https://github.com/adoptium/temurin-build/blob/master/RELEASING.md) captures what activities must happen during a release.  

The target release date is: March 22, 2022 

Release champion for this release is: @sxa (Stewart)
Release champion 'trainee': @smlambert (Shelley)

<details> 
<summary>Roles/Absences/Retrospective</summary>

Planned absences during the release cycle: TBD

The role of the release champion is to ensure that all release activities listed in this checklist get completed (by delegation to the broader release team or by the release champion themselves).  The final task of the release champion during a release is to confirm that all items in the checklist were completed satisfactorily and the release can be declared complete.

Everyone participating in a release, including the release champion are requested to provide feedback into the release retrospective (https://github.com/adoptium/adoptium/issues/128) so that the release process can be continuously improved (through simplification and/or automation).
</details>

-------

**One Week Prior to Release Checklist Items:**
<details>
<summary>Completed One Week Prior to Release Checklist Items</summary>

- [x] **Release Champion named** whose responsibility is to ensure every item in this checklist gets completed
- [x] **Declare code freeze** to ensure stability of build systems and infrastructure during release process
- [x] **Disable nightly testing** to free up resources and ensure no competing jobs during release week
- [x] **Run a trial release pipeline** to ensure less surprises on release day (typically against a milestone build)
</details>

-------

**Release Week Initial** Checklist Items:

<details>
<summary>Completed Release Week Initial Checklist Items</summary>

- [x] **Add website banner** (_automate_* via github workflow in website repository) - Announce that we target releases to be available within 48-72 hours of the GA tags being available
- [x] **Check Tags have been released upstream** - Look for mailing list announcements and `-ga` tags in version control.
- [x] **Check Tags have been Mirrored** [Mirrors](https://ci.adoptopenjdk.net/view/git-mirrors/job/git-mirrors/job/adoptium/).
- [x] **Launch build pipelines** for each version being released [(as per release doc](https://github.com/adoptium/temurin-build/blob/master/RELEASING.md#steps-for-every-version)) once release tags are available via [launch page](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/build) in Jenkins.  Provide links in this issue to each version's pipeline build(s). There may be multiple pipelines per version if primary and secondary platforms are separated to expedite the release.  In some cases,  where there are unforeseen configuration or infrastructure issues, reruns may be needed.
  - jdk18 pipeline(s):
    - **primary jdk18 pipeline:** https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk18-pipeline/151/
      - rerun(s): https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk18-pipeline/153/ (AIX/Win/Mac/Linux on p and z)
- [x] **Summarize test results**.  Find each launched build pipeline in [TRSS](https://trss.adoptium.net/) to view a summary of test results.  Can use the Release Summary Report feature in TRSS to generate a summary of failures, history and possible issues in markup format to be added to this issue as a comment.
- [x] **Triage** each build and test failure in the release summary report (following the [Triage guidelines](https://github.com/adoptium/aqa-tests/blob/master/doc/Triage.md)) and determine blocking or non-blocking.  Supply links to triage issues or docs for each version here.
  - jdk18 triage summary: https://github.com/adoptium/adoptium/issues/133
</details>

-------

**Platform specific Checklist Items:** 
<details>
<summary>Primary Platforms (x64 Linux 👍 , x64 Mac 👍 , x64 Windows 👍) Complete</summary>

- [x] **Confirm AQAvit results** satisfactory
- [x] **Confirm Temurin-compliance items completed**, per platform/version/binaryType
- [x] **Get PMC 'ready to publish' approval**, once no blocking failures exist.
- [x] **Publish the release** (run the restricted access [release tool job](https://ci.adoptopenjdk.net/job/build-scripts/job/release/job/refactor_openjdk_release_tool/) on Jenkins)
- [x] **Verify binaries published successfully** to github releases repo and website (_automate_*, this could also be an automated test)
</details>

<details>
<summary>Secondary Platforms / Linux ([aarch64 👍 , alpine-linux 👍 , arm32 👍 , ppc64le 👍 , s390x 👍 ]) Complete</summary>

- [x] **Confirm AQAvit results** satisfactory
- [ ] **Confirm Temurin-compliance items completed**, per platform/version/binaryType
- [ ] **Get PMC 'ready to publish' approval**, once no blocking failures exist.
- [ ] **Publish the release** (run the restricted access [release tool job](https://ci.adoptopenjdk.net/job/build-scripts/job/release/job/refactor_openjdk_release_tool/) on Jenkins)
- [ ] **Verify binaries published successfully** to github releases repo and website (_automate_*, this could also be an automated test)
</details>

<details open>
<summary>Secondary Platforms / Other (x32 Win 👍 , aarch64 Mac 👍, ppc64 AIX ⏳)</summary>

- [x] **Confirm AQAvit results** satisfactory
- [ ] **Confirm Temurin-compliance items completed**, per platform/version/binaryType
- [ ] **Get PMC 'ready to publish' approval**, once no blocking failures exist.
- [ ] **Publish the release** (run the restricted access [release tool job](https://ci.adoptopenjdk.net/job/build-scripts/job/release/job/refactor_openjdk_release_tool/) on Jenkins)
- [ ] **Verify binaries published successfully** to github releases repo and website (_automate_*, this could also be an automated test)
</details>

-------

**Publish and Comms Checklist Items:**
<details open>
<summary>Publish and Comms Checklist Items</summary>

- [x] **Publish updates to the containers to dockerhub** - Doc at [containers#update-official-docker-hub-manifest](https://github.com/adoptium/containers#update-official-docker-hub-manifest) and PR at [docker-library/official-images/pull/12192](https://github.com/docker-library/official-images/pull/12192)
- [x] **Edit the [Homebrew Temurin Cask](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/temurin.rb)** and replace the version and sha256 as appropriate.  This means for Homebrew users that they install the latest by default and can use the `@` notation to install older versions if they wish. PR at [homebrew-cask/pull/121514](https://github.com/Homebrew/homebrew-cask/pull/121514)
- [x] **Update support page** (_automate_* github workflow to create a PR to update [support.handlebars](https://github.com/adoptium/adoptium.net/blob/master/src/handlebars/support.handlebars))
- [ ] **Update release notes** (_automate_* - github workflow to create update for [release notes page](https://adoptium.net/release_notes.html))
- [x] **Trigger linux installers pipeline** - related PR at [installer/pull/450](https://github.com/adoptium/installer/pull/450), installer pipeline run at [adoptium-packages-linux-pipeline/84](https://ci.adoptopenjdk.net/job/adoptium-packages-linux-pipeline/84)
- [x] **Publicize the release** via Slack #release channel and Twitter (can be partially automated)
- [x] **Declare code freeze end** opening up the code for further development
- [x] **Re-enable nightly testing** by reverting the PR that excluded it
- [x] **Remove website banner** (_automate_* via github workflow in website repository)
- [x] **Declare the release complete** and close this issue
</details>

**Comment by tellison** [comment]
My 2c.... It would be good for the 'release champion trainee' to lead the release by following the documentation, with the experienced champion watching and answering clarifying questions. That way the new champion gets the real experience, and we test whether our checklist steps and documentation of those are sufficient.

**Comment by smlambert** [comment]
Indeed we are doing as suggested in https://github.com/adoptium/adoptium/issues/130#issuecomment-1074900323 and have already hit a case that is not sufficiently documented.  Trainee is making notes to add to the retrospective (and update the already too long documentation).

**Comment by luisuimi** [comment]
Open

**Comment by smlambert** [comment]
9 of 11 platforms are published and available via api.adoptium.net (https://api.adoptium.net/v3/assets/feature_releases/18/ga?image_type=jdk&vendor=eclipse for the listing).

- the remaining 2 (aarch64 Mac and ppc64 AIX) that are not yet published, awaiting TCK completion.

**Comment by smlambert** [comment]
Release notes item in checklist is dependent on https://github.com/adoptium/website-v2/issues/103

**Comment by smlambert** [comment]
Marking this issue and the release as closed, even though there are 2 dangling items from the checklist:
- AIX platform will not be released on this round 
- Release notes blocked on and tracked in [adoptium/website-v2/issues/103](https://github.com/adoptium/website-v2/issues/103)
