### ISSUE TITLE
Checklist for Temurin Release jdk-8u332, jdk-11.0.15, jdk-17.0.3 and jdk-18.0.1

### ISSUE THREAD

**Issue by Haroon-Khel** [adoptium/adoptium#139]
This Temurin release checklist based on the [release doc](https://github.com/adoptium/temurin-build/blob/master/RELEASING.md) captures what activities must happen during a release.  

The target release date is: 25/4/2022 (Main Platforms)

The release champion (trainee) for this release is: Haroon Khel @Haroon-Khel 

Planned absences during the release cycle: 

The role of the release champion is to ensure that all release activities listed in this checklist get completed (by delegation to the broader team or by the release champion themselves).  The final task of the release champion during a release is to confirm that all items in the checklist were completed satisfactorily and the release can be declared complete.

Everyone participating in a release, including the release champion are requested to provide feedback into the release retrospective so that the release process can be continuously improved (through simplification and/or automation).

-------

One Week Prior to Release:

- [x] **Release Champion named** whose responsibility is to ensure every item in this checklist gets completed
- [x] **Declare code freeze** to ensure stability of build systems and infrastructure during release process
- [x] **Disable nightly testing** to free up resources and ensure no competing jobs during release week
- [x] **Run a trial release pipeline** to ensure less surprises on release day (typically against a milestone build)

-------

Release Week Checklist:

- [x] **Add website banner** (_automate_* via github workflow in website repository) - Announce that we target releases to be available within 48-72 hours of the GA tags being available
- [x] **Check Tags have been released upstream** - Look for mailing list announcements and `-ga` tags in version control.
- [x] **Check Tags have been Mirrored** [Mirrors](https://ci.adoptopenjdk.net/view/git-mirrors/job/git-mirrors/job/adoptium/).
- [x] **Launch build pipelines** for each version being released [(as per release doc](https://github.com/adoptium/temurin-build/blob/master/RELEASING.md#steps-for-every-version)) once release tags are available via [launch page](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/build) in Jenkins.  Provide links in this issue to each version's pipeline build(s). There may be multiple pipelines per version if primary and secondary platforms are separated to expedite the release.  In some cases,  where there are unforeseen configuration or infrastructure issues, reruns may be needed.
  - jdk8 pipeline(s):
    - **primary jdk8 pipeline:** https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/2087/
      - rerun(s): (Win32) https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/2094/
    - **secondary jdk8 pipeline:**
      - reruns(s):
  - jdk11 pipeline(s):
    - **primary jdk11 pipeline:**
    - https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/1910/console
      - rerun(s):
    - **secondary jdk11 pipeline:**
      - rerun(s):
  - jdk17 pipeline(s):
    - **primary jdk17 pipeline:**
    - https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk17-pipeline/348/
      - rerun(s): 
    - **secondary jdk17 pipeline:**
      - rerun(s):
  - jdk18 pipeline(s):
    - **primary jdk18 pipeline:**
    - https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk18-pipeline/170/
      - rerun(s): Mac x64 only https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk18-pipeline/173/console
    - **secondary jdk18 pipeline:**
      - rerun(s): 
- [x] **Add links to the [status doc](https://github.com/adoptium/adoptium/issues/140)** to indicate per-platform builds ready
- [x] **Summarize test results**.  Find each launched build pipeline in [TRSS](https://trss.adoptium.net/) to view a summary of test results.  Can use the Release Summary Report feature in TRSS to generate a summary of failures, history and possible issues in markup format to be added to this issue as a comment.
- [x] **Triage** each build and test failure in the release summary report (following the [Triage guidelines](https://github.com/adoptium/aqa-tests/blob/master/doc/Triage.md)) and determine blocking or non-blocking.  Supply links to triage issues or docs for each version here.
  - jdk8 triage summary: https://github.com/adoptium/aqa-tests/issues/3603
  - jdk11 triage summary: https://github.com/adoptium/aqa-tests/issues/3596
  - jdk17 triage summary: https://github.com/adoptium/aqa-tests/issues/3594
  - jdk18 triage summary: https://github.com/adoptium/aqa-tests/issues/3599
- [x] **Fix** blocking failures if they exist and confirm others are non-blocking.
- [x] **Confirm Temurin-compliance items completed**, per platform/version/binaryType
- [x] **Get PMC 'ready to publish' approval**, once no blocking failures exist.
- [x] **Publish the release** (run the restricted access [release tool job](https://ci.adoptopenjdk.net/job/build-scripts/job/release/job/refactor_openjdk_release_tool/) on Jenkins)
- [x] **Verify binaries published successfully** to github releases repo and website (_automate_*, this could also be an automated test)

- [x] **Publish updates to the containers to dockerhub**
- [x] **Edit the [Homebrew Temurin Cask](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/temurin.rb) and replace the version and sha256 as appropriate.  This means for Homebrew users that they install the latest by default and can use the `@` notation to install older versions if they wish.
- [ ] **Update support page** (_automate_* github workflow to create a PR to update [support.handlebars](https://github.com/adoptium/adoptium.net/blob/master/src/handlebars/support.handlebars))
- [ ] **Update release notes** (_automate_* - github workflow to create update for [release notes page](https://adoptium.net/release_notes.html))
- [x] **Trigger linux installers pipeline** currently it is part of the build pipelines (will eventually be updated to run independently)
- [ ] **Publicize the release** via Slack #release channel and Twitter (can be partially automated)
- [x] **Declare code freeze end** opening up the code for further development
- [x] **Remove website banner** (_automate_* via github workflow in website repository)
- [x] **Check for presence of jdk8u aarch32 GA tag and mirror it** [Mercurial repo](https://hg.openjdk.java.net/aarch32-port/jdk8u) - [Mirror job](https://ci.adoptopenjdk.net/view/git-mirrors/job/git-mirrors/job/adoptium/job/git-hg-aarch32-jdk8u/)
- [x] **Do all of the above for the jdk8u/aarch32 build**
- [ ] **Declare the release complete** and close this issue

**Comment by mfriess2** [comment]
Is there a timeline when the 8u332 docker images will be published to Docker Hub?
Currently we see us forced to switch to other Java distribution images because they are already released, which is unfortunate.

**Comment by smlambert** [comment]
re: https://github.com/adoptium/adoptium/issues/139#issuecomment-1118713182, believe we are just waiting on this PR https://github.com/docker-library/official-images/pull/12366 to be merged for the jdk8u332-b09 images to be available

**Comment by mfriess2** [comment]
Okay, thanks for the update and your maintenance work!
