### ISSUE TITLE
Checklist for Temurin Release jdk-18.0.2+9, jdk-17.0.4+8, jdk-11.0.16+8, jdk-8u342-b07

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/adoptium#152]
This Temurin release checklist based on the [release doc](https://github.com/adoptium/temurin-build/blob/master/RELEASING.md) captures what activities must happen during a release.  

The target release date is: July 19, 2022

The release champion for this release is: Sophia Guo @sophia-guo 

Planned absences during the release cycle: sxa 4-7 August

The role of the release champion is to ensure that all release activities listed in this checklist get completed (by delegation to the broader team or by the release champion themselves).  The final task of the release champion during a release is to confirm that all items in the checklist were completed satisfactorily and the release can be declared complete.

Everyone participating in a release, including the release champion are requested to provide feedback into the release retrospective so that the release process can be continuously improved (through simplification and/or automation).

-------

One Week Prior to Release:

- [x] **Release Champion named** whose responsibility is to ensure every item in this checklist gets completed
- [x] **Declare code freeze** to ensure stability of build systems and infrastructure during release process
- [x] **Disable nightly testing** to free up resources and ensure no competing jobs during release week
- [x] **Run a trial release pipeline** to ensure less surprises on release day (typically against a milestone build)

-------

Release Week Checklist:

- [x] **Add website banner** (_automate_* via github workflow in website repository) - Announce that we target releases to be available within 48-72 hours of the GA tags being available
- [x] **Check Tags have been released upstream** - Look for mailing list announcements and `-ga` tags in version control.
- [x] **Check Tags have been Mirrored** [Mirrors](https://ci.adoptopenjdk.net/view/git-mirrors/job/git-mirrors/job/adoptium/).
- [x] **Launch build pipelines** for each version being released [(as per release doc](https://github.com/adoptium/temurin-build/blob/master/RELEASING.md#steps-for-every-version)) once release tags are available via [launch page](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/build) in Jenkins.  Provide links in this issue to each version's pipeline build(s). There may be multiple pipelines per version if primary and secondary platforms are separated to expedite the release.  In some cases,  where there are unforeseen configuration or infrastructure issues, reruns may be needed.
  - **aqaReference: v0.9.3-release**
  - jdk8 pipeline(s):
    - **primary jdk8 pipeline:** https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/2202/
      - rerun(s):  (Win+Mac due to 502s on the signing server) https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/2204/
    - **secondary jdk8 pipeline (ARM32):** (Win+Mac due to 502s on the signing server) https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/2203/
    - reruns(s):
        - gdams **Win32 to revert compiler upgrade:** https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/2208/ ---> sophia-guo : Should be win64?
         -  **SXA 2022/08/02 ALL JDK8 EXCECPTION WIN+ARM32 for jdk8u345** https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/2212/
        - **SXA 2022/08/02 Win64 (To prioritise over Win32) including `--with-toolchain-version=2013` override in parameters:** https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/2216
        - **SXA 2022/08/02 Win32**: https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/2217
        - ARM32: TBC
  - jdk11 pipeline(s):
    - **primary jdk11 pipeline:** https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/2028/
      - rerun(s): https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/2029/ (windows VS2017 revert)
    - **11.0.16.1 jdk11 pipeline:** https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/2043/
    - **11.0.16.1 jdk11 Win64 pipeline (compiler switch):** https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/2044/
      - rerun(s):
  - jdk17 pipeline(s):
    - **primary jdk17 pipeline:** https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk17-pipeline/463/
      - rerun(s): (WIn32) https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk17-pipeline/465
    - **17.0.4.1 jdk17 pipeline:** https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk17-pipeline/480/
      - rerun(s):
  - jdk18 pipeline(s):
    - **primary jdk18 pipeline:** https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk18-pipeline/229/
      - rerun(s):
    - **18.0.2.1+1 jdk18 pipeline:** https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk18-pipeline/250
      - rerun(s):
      
- [x] **Add links to the [status doc](https://github.com/adoptium/adoptium/issues/153)** to indicate per-platform builds ready
- [x] **Summarize test results**.  Find each launched build pipeline in [TRSS](https://trss.adoptium.net/) to view a summary of test results.  Can use the Release Summary Report feature in TRSS to generate a summary of failures, history and possible issues in markup format to be added to this issue as a comment.
- [x] **Triage** each build and test failure in the release summary report (following the [Triage guidelines](https://github.com/adoptium/aqa-tests/blob/master/doc/Triage.md)) and determine blocking or non-blocking.  Supply links to triage issues or docs for each version here.
  - jdk8 triage summary: https://github.com/adoptium/aqa-tests/issues/3880 https://github.com/adoptium/aqa-tests/issues/3904
  - jdk11 triage summary: https://github.com/adoptium/aqa-tests/issues/3868 https://github.com/adoptium/aqa-tests/issues/3924
  - jdk17 triage summary: https://github.com/adoptium/aqa-tests/issues/3869 https://github.com/adoptium/aqa-tests/issues/3925
  - jdk18 triage summary: https://github.com/adoptium/aqa-tests/issues/3872
- [x] **Fix** blocking failures if they exist and confirm others are non-blocking.
- [x] **Confirm Temurin-compliance items completed**, per platform/version/binaryType
- [x] **Get PMC 'ready to publish' approval**, once no blocking failures exist.
- [x] **Publish the release** (run the restricted access [release tool job](https://ci.adoptopenjdk.net/job/build-scripts/job/release/job/refactor_openjdk_release_tool/) on Jenkins)
- [x] **Verify binaries published successfully** to github releases repo and website (_automate_*, this could also be an automated test)

- [x] **Publish updates to the containers to dockerhub**
- [x] **Edit the [Homebrew Temurin Cask](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/temurin.rb) and replace the version and sha256 as appropriate.  This means for Homebrew users that they install the latest by default and can use the `@` notation to install older versions if they wish.
- [x] **Update support page** (_automate_* github workflow to create a PR to update [support.handlebars](https://github.com/adoptium/adoptium.net/blob/master/src/handlebars/support.handlebars))
    - https://github.com/adoptium/website-v2/pull/864
- [x] **Update release notes** (_automate_* - github workflow to create update for [release notes page](https://adoptium.net/release_notes.html))
- [x] **Trigger linux installers pipeline** currently it is part of the build pipelines (will eventually be updated to run independently)
- [x] **Publicize the release** via Slack #release channel and Twitter (can be partially automated)
- [x] **Declare code freeze end** opening up the code for further development
- [x] **Remove website banner** (_automate_* via github workflow in website repository)
- [x] **Check for presence of jdk8u aarch32 GA tag and mirror it** [Mercurial repo](https://hg.openjdk.java.net/aarch32-port/jdk8u) - [Mirror job](https://ci.adoptopenjdk.net/view/git-mirrors/job/git-mirrors/job/adoptium/job/git-hg-aarch32-jdk8u/)
- [x] **Do all of the above for the jdk8u/aarch32 build**
- [x] **Declare the release complete** and close this issue

**Comment by RonneGisun** [comment]
@sophia-guo Wondering if you are aware? I just tried installing Java 11 jdk on Centos 7, but got an error:
'Package temurin-11-jdk-11.0.16.0.0.8-1.x86_64.rpm is not signed.'
Is this release still pending?

**Comment by zdtsw** [comment]
> @sophia-guo Wondering if you are aware? I just tried installing Java 11 jdk on Centos 7, but got an error: 'Package temurin-11-jdk-11.0.16.0.0.8-1.x86_64.rpm is not signed.' Is this release still pending?

Thanks for letting us know!
Yes, we are working on the fix at the moment.

**Comment by sxa** [comment]
> @sophia-guo Wondering if you are aware? I just tried installing Java 11 jdk on Centos 7, but got an error: 'Package temurin-11-jdk-11.0.16.0.0.8-1.x86_64.rpm is not signed.' Is this release still pending?

Yup I spotted that and reported to @sophia-guo so we are aware

**Comment by RonneGisun** [comment]
> > @sophia-guo Wondering if you are aware? I just tried installing Java 11 jdk on Centos 7, but got an error: 'Package temurin-11-jdk-11.0.16.0.0.8-1.x86_64.rpm is not signed.' Is this release still pending?
> 
> Thanks for letting us know! Yes, we are working on the fix at the moment.

Yep, working now. Thanks.

**Comment by vladislav-orlovskiy** [comment]
> > @sophia-guo Wondering if you are aware? I just tried installing Java 11 jdk on Centos 7, but got an error: 'Package temurin-11-jdk-11.0.16.0.0.8-1.x86_64.rpm is not signed.' Is this release still pending?
> 
> Yup I spotted that and reported to @sophia-guo so we are aware

something similar for deb package.
ubuntu 18.04

`Err:1 https://adoptium.jfrog.io/artifactory/deb bionic/main amd64 temurin-11-jdk amd64 11.0.16.0.0+8
  403  Forbidden [IP: 18.64.100.119 443]
E: Failed to fetch https://d3d227kvr2djy5.cloudfront.net/filestore/e2/e2fbf7f3c0a21c84abae0f048122ce52be5f663a?response-content-type=application/x-debian-package&x-jf-traceId=17db05d82d280c1&X-Artifactory-repositoryKey=deb&X-Artifactory-projectKey=temurin&X-Artifactory-artifactPath=pool/main/t/temurin-11/temurin-11-jdk_11.0.16.0.0+8_amd64.deb&X-Artifactory-username=anonymous&Expires=1659393555&Signature=OCwjdstrcIKvjv0Oqbzo-oRCmnsks8RkYecmLKVX4KnK8GNhVxSzOciyrPa~fm~hQLF~YiKn6BM4UygkOOvZNHZOwaiRHG95XjW~bMiPCOUCti7Foy7Suq9Cceb0gABYdoAMOZ~5K5Rs2A71Ud2JoXchSm0yZEil94kPpUgEfVDGbrsnLgqtXMbbXglDRxoLaldsOGxDjsFg2887PDOoDtjO3kvGir09GiNgGxVWApy029en0vJ-a-bWra9UDaCU9E4hRgEkpBjZXPIr-9cQZcbwbNNpbt5DwPTxDftrcT3A3GBy5OjYdCs-5oZiFqRuqKl10HQuzb3bvXZtkS3v8Q__&Key-Pair-Id=APKAJ6NHFWMVU3M6DPBA  403  Forbidden `

**Comment by zdtsw** [comment]
> > > @sophia-guo Wondering if you are aware? I just tried installing Java 11 jdk on Centos 7, but got an error: 'Package temurin-11-jdk-11.0.16.0.0.8-1.x86_64.rpm is not signed.' Is this release still pending?
> > 
> > 
> > Yup I spotted that and reported to @sophia-guo so we are aware
> 
> something similar for deb package. ubuntu 18.04
> 
> `Err:1 https://adoptium.jfrog.io/artifactory/deb bionic/main amd64 temurin-11-jdk amd64 11.0.16.0.0+8 403 Forbidden [IP: 18.64.100.119 443] E: Failed to fetch https://d3d227kvr2djy5.cloudfront.net/filestore/e2/e2fbf7f3c0a21c84abae0f048122ce52be5f663a?response-content-type=application/x-debian-package&x-jf-traceId=17db05d82d280c1&X-Artifactory-repositoryKey=deb&X-Artifactory-projectKey=temurin&X-Artifactory-artifactPath=pool/main/t/temurin-11/temurin-11-jdk_11.0.16.0.0+8_amd64.deb&X-Artifactory-username=anonymous&Expires=1659393555&Signature=OCwjdstrcIKvjv0Oqbzo-oRCmnsks8RkYecmLKVX4KnK8GNhVxSzOciyrPa~fm~hQLF~YiKn6BM4UygkOOvZNHZOwaiRHG95XjW~bMiPCOUCti7Foy7Suq9Cceb0gABYdoAMOZ~5K5Rs2A71Ud2JoXchSm0yZEil94kPpUgEfVDGbrsnLgqtXMbbXglDRxoLaldsOGxDjsFg2887PDOoDtjO3kvGir09GiNgGxVWApy029en0vJ-a-bWra9UDaCU9E4hRgEkpBjZXPIr-9cQZcbwbNNpbt5DwPTxDftrcT3A3GBy5OjYdCs-5oZiFqRuqKl10HQuzb3bvXZtkS3v8Q__&Key-Pair-Id=APKAJ6NHFWMVU3M6DPBA 403 Forbidden `

Hi @vladislav-orlovskiy  this is a different issue, but we are trying to fix it now.
