### ISSUE TITLE
Checklist for Temurin Release jdk-19.0.1, jdk-17.0.5, jdk-11.0.17, jdk-8u352

### ISSUE THREAD

**Issue by zdtsw** [adoptium/adoptium#179]
This Temurin release checklist based on the [release doc](https://github.com/adoptium/temurin-build/blob/master/RELEASING.md) captures what activities must happen during a release.  

The target release date is:  18th Oct 2022

The release champion for this release is:  Wen Zhou @zdtsw 

Planned absences during the release cycle: 

The role of the release champion is to ensure that all release activities listed in this checklist get completed (by delegation to the broader team or by the release champion themselves).  The final task of the release champion during a release is to confirm that all items in the checklist were completed satisfactorily and the release can be declared complete.

Everyone participating in a release, including the release champion are requested to provide feedback into the release retrospective so that the release process can be continuously improved (through simplification and/or automation).

-------

One Week Prior to Release:

- [x] **Release Champion named** whose responsibility is to ensure every item in this checklist gets completed
- [x] **Declare code freeze** to ensure stability of build systems and infrastructure during release process. This is done by pasting the below message into the #release channel in Slack:
  
<details>
<summary>Code Freeze message</summary>

With under a week to go until releases, we are entering a lockdown period for the following repositories: <a href='https://github.com/adoptium/temurin-build/pulls'>temurin-build</a>, <a href='https://github.com/adoptium/ci-jenkins-pipelines/pulls'>ci-jenkins-pipelines</a>, <a href='https://github.com/adoptium/github-release-scripts/pulls'>github-release-scripts</a>, <a href='https://github.com/adoptium/containers/pulls'>containers</a>, <a href='https://github.com/adoptium/installer/pulls'>installer</a> <a href="https://github.com/adoptium/jenkins-helper/pulls">jenkins-helper</a>.
If you need to submit a pr for any of these repos during this period, you should:
  <ul>
  <li>Add a comment saying “Approval to merge during the lockdown cycle please” and post in the appropriate slack channel for awareness. This can be done before the PR is finalised</li>
  <li>Add a note into this channel saying you are requesting the approval with a link to the comment in the first bullet point</li>
  <li>The comment should have approval from at least one build committer and one PMC member to indicate that they agree it is critical that it goes in</li>
  <li>The PR can be merged after 2 hours of the post going into the build channel (to give people time to object ... This delay may be skipped in the case where the delay will result in something breaking within that time.</li>
  </ul>
</details>

- [x] **Disable nightly testing** to free up resources and ensure no competing jobs during release week
- [x] **Update aqaReference** to update with new git tag for 'aqaReference' to be used in release pipeline
- [x] **Run a trial release pipeline** to ensure less surprises on release day (typically against a milestone build)

-------

Release Week Checklist:

- [x] **Add website banner** (_automate_* via github workflow in website repository) - Announce that we target releases to be available within[ 48-72 hours](https://github.com/adoptium/website-v2/blob/main/src/components/Banner.tsx#L3) of the GA tags being available
- [x] **Check Tags have been released upstream** - Look for mailing list announcements and `-ga` tags in version control.
- [x] **Check Tags have been Mirrored** [Mirrors](https://ci.adoptopenjdk.net/view/git-mirrors/job/git-mirrors/job/adoptium/).
- [x] **Launch build pipelines** for each version being released [(as per release doc](https://github.com/adoptium/temurin-build/blob/master/RELEASING.md#steps-for-every-version)) once release tags are available via [launch page](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/build) in Jenkins.  Provide links in this issue to each version's pipeline build(s). There may be multiple pipelines per version if primary and secondary platforms are separated to expedite the release.  In some cases,  where there are unforeseen configuration or infrastructure issues, reruns may be needed.
  - [x] jdk8 pipeline(s):
    - **primary jdk8 pipeline:** 
      -  Except Winx64,Arm32Linux: https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/2322
      -  Windowsx64: https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/2320
      - rerun(s): **X64Mac** https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/2323/
    - [x] **secondary jdk8 pipeline(arm32Linux):** https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/2326
      - reruns(s): fix final tarball name https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/2333
  - [x] jdk11 pipeline(s):
    - **primary jdk11 pipeline:** 
      - Except Windows64: https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/2121/
      - Windowsx64:  https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/2122
      - rerun(s):
    - **secondary jdk11 pipeline**:
      - rerun(s):
  - [x]  jdk17 pipeline(s):
    - **primary jdk17 pipeline:** https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk17-pipeline/539
      - rerun(s):
    - **secondary jdk17 pipeline:**
      - rerun(s):
  - [x] jdk19 pipeline(s):
    - **primary jdk19 pipeline:** https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk19-pipeline/237
      - rerun(s): WindowsX64 https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk19-pipeline/238
    - **secondary jdk19 pipeline:**
      - rerun(s): 
 - [ ] **Update release notes** (_automate_* - github workflow to create update for [release notes page](https://adoptium.net/release_notes.html)) 
- [x] **Add links to the [status doc](https://github.com/adoptium/adoptium/issues/180)** to indicate per-platform builds ready
- [x] **Summarize test results**.  Find each launched build pipeline in [TRSS](https://trss.adoptium.net/) to view a summary of test results.  Can use the Release Summary Report feature in TRSS to generate a summary of failures, history and possible issues in markup format to be added to this issue as a comment.
- [x] **Triage** each build and test failure in the release summary report (following the [Triage guidelines](https://github.com/adoptium/aqa-tests/blob/master/doc/Triage.md)) and determine blocking or non-blocking.  Supply links to triage issues or docs for each version here.
  - [x] jdk8 triage summary: https://github.com/adoptium/aqa-tests/issues/4041
  - [x] jdk11 triage summary: https://github.com/adoptium/aqa-tests/issues/4038
  - [x] jdk17 triage summary: https://github.com/adoptium/aqa-tests/issues/4039
  - [x] jdk19 triage summary: https://github.com/adoptium/aqa-tests/issues/4040
- [x] **Fix** blocking failures if they exist and confirm others are non-blocking.
- [x] **Confirm Temurin-compliance items completed**, per platform/version/binaryType
- [x] **Get PMC 'ready to publish' approval**, once no blocking failures exist.
- [x] **Publish the release** (run the restricted access [release tool job](https://ci.adoptopenjdk.net/job/build-scripts/job/release/job/refactor_openjdk_release_tool/) on Jenkins)
- [x] **Verify binaries published successfully** to github releases repo and website (_automate_*, this could also be an automated test)

- [x] **Publish updates to the containers to dockerhub**
   - [x] jdk8
   - [x] jdk11
   - [x] jdk17
   - [x] jdk19 
- [x] **Edit the [Homebrew Temurin Cask](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/temurin.rb) and replace the version and sha256 as appropriate**  This means for Homebrew users that they install the latest by default and can use the `@` notation to install older versions if they wish
- [x] **Update support page** (automate* github workflow to create a PR to update [release-roadmap](https://github.com/adoptium/website-v2/blob/main/src/asciidoc-pages/support.adoc#release-roadmap))
- [x] **Trigger linux installers pipeline** currently it is part of the build pipelines (will eventually be updated to run independently)
   - [x] jdk8
   - [x] jdk11
   - [x] jdk17
   - [x] jdk19 
- [ ] **Publicize the release** via Slack #release channel and Twitter (can be partially automated)
- [x] **Declare code freeze end** opening up the code for further development
- [x] **Enable nightly testing** 
- [x] **Remove website banner** (_automate_* via github workflow in website repository)
- [x] **Check for presence of jdk8u aarch32 GA tag and mirror it** [Mercurial repo](https://hg.openjdk.java.net/aarch32-port/jdk8u) - [Mirror job](https://ci.adoptopenjdk.net/view/git-mirrors/job/git-mirrors/job/adoptium/job/git-hg-aarch32-jdk8u/)
- [x] **Do all of the above for the jdk8u/aarch32 build**
- [ ] **Declare the release complete** and close this issue

**Comment by mrMigles** [comment]
Hi,
could you please tell when can we see release eclipse-temurin jdk-8u352? May be need some help with PR, I don't see such one.

**Comment by zdtsw** [comment]
> Hi, could you please tell when can we see release eclipse-temurin jdk-8u352? May be need some help with PR, I don't see such one.

For detail release progress of each platform, please follow https://github.com/adoptium/adoptium/issues/180

As for "May be need some help with PR", can you explain a bit more what you mean?

**Comment by mrMigles** [comment]
HI @zdtsw,
Thank you for the info, 
I meant if we can provide PR for update JDK to 352 by our own, but I had no idea how does upgrade process looks in adoptium :). 
Now I see that auto PR with upgrade JDK appeared https://github.com/adoptium/containers/pull/304.

**Comment by jprante** [comment]
I can not see RPM release at https://packages.adoptium.net/ui/repos/tree/General/rpm/rhel/9/x86_64/Packages maybe I miss something important?

**Comment by zdtsw** [comment]
> I can not see RPM release at https://packages.adoptium.net/ui/repos/tree/General/rpm/rhel/9/x86_64/Packages maybe I miss something important?

it depends on which jdk version you are looking for.
So far, we only released jdk8 for x64 rpm.

**Comment by zdtsw** [comment]
> > I can not see RPM release at https://packages.adoptium.net/ui/repos/tree/General/rpm/rhel/9/x86_64/Packages maybe I miss something important?
> 
> it depends on which jdk version you are looking for. So far, we only released jdk8 for x64 rpm.

Now, we've released all packages on 4 jdk versions, please let me know if you still have problem to get any @jprante

**Comment by zdtsw** [comment]
close issue as most of the work has been completed
