### ISSUE TITLE
Temurin Compliance Improvements Checklist: Q1 2023

### ISSUE THREAD

**Issue by jiekang** [adoptium/adoptium#206]
Placeholder to track compliance work for project planning

- [x] https://github.com/temurin-compliance/temurin-compliance/issues/151
- [x] https://github.com/temurin-compliance/temurin-compliance/issues/225
- [x] https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2032
- [x] https://github.com/temurin-compliance/temurin-compliance/issues/347

**Comment by smlambert** [comment]
This is now completed.
