### ISSUE TITLE
Checklist for Temurin Release  jdk-17

### ISSUE THREAD

**Issue by smlambert** [adoptium/adoptium#73]
This Temurin release checklist based on the [release doc](https://github.com/adoptium/temurin-build/blob/master/RELEASING.md) captures what activities must happen during a release.  

The target release dates are: 
- Tag expected on Sept 14
- TCK test material expected days later (Sept 17?)
- Sept 2021 [Release report](https://github.com/adoptium/adoptium#workspaces/adoptium-60d93da7bf5a0e0019b82131/reports/release?repos=85294562,346036596,346513536,353769915)

The release champion for this release is: **Martijn Verburg**
Temurin-compliance status from: Andrew Leonard, Shelley Lambert
AQAvit triage support from: Sophia Guo, Shelley Lambert
Unavailable for release week: Stewart Addison, Simon Rushton

The role of the release champion is to ensure that all release activities listed in this checklist get completed (by delegation to the broader team or by the release champion themselves).  The final task of the release champion during a release is to confirm that all items in the checklist were completed satisfactorily and the release can be declared complete.

Everyone participating in a release, including the release champion are requested to provide feedback into the release retrospective so that the release process can be continuously improved (through simplification and/or automation).

-------

One Week Prior to Release:

- [x] **Release Champion named** whose responsibility is to ensure every item in this checklist gets completed
- [ ] **Declare code freeze** to ensure stability of build systems and infrastructure during release process
- [ ] **Disable nightly testing** to free up resources and ensure no competing jobs during release week
- [ ] **Update list of CA certificates** if required, following this [security/README](https://github.com/adoptium/temurin-build/blob/master/security/README.md)
- [ ] **Run a trial release pipeline** to ensure less surprises on release day (typically against a milestone build)

-------

Release Week Checklist:

- [ ] **Add website banner** (_automate_* via github workflow in website repository) - Announce that we target releases to be available within 48-72 hours of the GA tags being available
- [ ] **Launch build pipelines** for each version being released [(as per release doc](https://github.com/adoptium/temurin-build/blob/master/RELEASING.md#steps-for-every-version)) once release tags are available via [launch page](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/build) in Jenkins.  Provide links in this issue to each version's pipeline build(s). There may be multiple pipelines per version if primary and secondary platforms are separated to expedite the release.  In some cases,  where there are unforeseen configuration or infrastructure issues, reruns may be needed.
  - jdk17 pipeline(s):
    - primary jdk17 pipeline:
      - rerun(s):
    - secondary jdk17 pipeline:
      - rerun(s):
- [ ] **Summarize test results**.  Find each launched build pipeline in [TRSS](https://trss.adoptium.net/) to view a summary of test results.  Can use the Release Summary Report feature in TRSS to generate a summary of failures, history and possible issues in markup format to be added to this issue as a comment.
- [ ] **Triage** each build and test failure in the release summary report (following the [Triage guidelines](https://github.com/adoptium/aqa-tests/blob/master/doc/Triage.md)) and determine blocking or non-blocking.  Supply links to triage issues or docs for each version here.
  - jdk17 triage summary:
- [ ] **Fix** blocking failures if they exist and confirm others are non-blocking.
- [ ] **Get PMC 'ready to publish' approval**, once no blocking failures exist.
- [ ] **Publish the release** (run the restricted access [release tool job](https://ci.adoptopenjdk.net/job/build-scripts/job/release/job/refactor_openjdk_release_tool/) on Jenkins)
- [ ] **Verify binaries published successfully** to github releases repo and website (_automate_*, this could also be an automated test)
- [ ] **Update support page** (_automate_* github workflow to create a PR to update [support.handlebars](https://github.com/adoptium/adoptium.net/blob/master/src/handlebars/support.handlebars))
- [ ] **Update release notes** (_automate_* - github workflow to create update for [release notes page](https://adoptium.net/release_notes.html))
- [ ] **Trigger linux installers pipeline** currently it is part of the build pipelines (will eventually be updated to run independently)
- [ ] **Publicize the release** via Slack #release channel and Twitter (can be partially automated)
- [ ] **Declare code freeze end** opening up the code for further development
- [ ] **Remove website banner** (_automate_* via github workflow in website repository)
- [ ] **Declare the release complete** and close this issue

TODO To migrate / reinstate later

- [ ] **Trigger docker images pipeline** via the [GitHub Actions job](https://github.com/AdoptOpenJDK/openjdk-docker/actions/workflows/updater.yml). Click Run Workflow, keep the branch as Master and click `Run Workflow`. This updater job checks the API and updates the relevant dockerfiles. A Pull Request is then created by the adoptopenjdk-bot account which will need merging once all the CI tests pass.  *TBD - how this step evolves for Temurin releases.
- [ ] **Update Official Docker Images** Once the dockerfiles have been updated in the previous step you can run the `dockerhub_doc_config_update.sh` script. This will create a file called adoptopenjdk which will need to be copy and pasted into the [official adoptopenjdk config](https://github.com/docker-library/official-images/blob/master/library/adoptopenjdk) [example PR](https://github.com/docker-library/official-images/pull/10083) *TBD - how this step evolves for Temurin releases.

**Comment by karianna** [comment]
One thing to note for users is that the vendor has been changed from `Eclipse Foundation` to `Eclipse Adoptium` after long debates at the Working Group :-).

**Comment by karianna** [comment]
Raised https://github.com/adoptium/aqa-test-tools/issues/541 to cover a mis firing of sending results to TRSS or a display bug in TRSS (not sure yet).

**Comment by karianna** [comment]
I'm pretty sure the Alpine Linux we produced was not headless as that PR hadn't landed yet - so will need to respin that one.

**Comment by CyberFlameGO** [comment]
Good to know :)

**Comment by System0x40** [comment]
Is there something we should know about the TCK phase?

**Comment by smlambert** [comment]
re: https://github.com/adoptium/adoptium/issues/73#issuecomment-922510718 - short answer is that its slow work to run the compliance suite of tests at the project

Here are some [stats for July release](https://github.com/adoptium/adoptium/issues/3#issuecomment-889401944), you can extrapolate from those what September release looks like in [Temurin-compliance project](https://projects.eclipse.org/projects/adoptium.temurin-compliance) where the TCKs are run. (more people and machines would be helpful).  Also noting, we also do not have early access to TCK test material, so we received them on Thursday/Sept16 afternoon and that is the very first chance we have had to run them against the Temurin binaries.

**Comment by bachp** [comment]
I don't know if this is the right place to report this. But is it expected that the arm (32-bit) release contains a `lib/client` and `lib/server` directory. While all other platforms only contain a `lib/server`.

I noticed it because both directories contain a `libjvm.so` and this confused bitbake.

**Comment by ffays** [comment]
Why the JRE assets are not part of the JDK 17+35 official release whereas they were included a couple hours ago by the nightly build (i.e. JDK 17 2021-09-22 02:48 beta) ?

cf.

- [jdk-17+35](https://github.com/adoptium/temurin17-binaries/releases/tag/jdk-17%2B35)
- [jdk17-2021-09-22-02-48-beta](https://github.com/adoptium/temurin17-binaries/releases/tag/jdk17-2021-09-22-02-48-beta)

Could you please include the JRE assets in the next official release ?

**Comment by karianna** [comment]
We are not releasing JREs (the ones being produced by the nightlies were for us to see what the (now-defunct) legacyJRE build target produces so we can build better docs / tooling for the post JRE world.

**Comment by dinvlad** [comment]
Could you elaborate why JREs are not released for 17? Is there a plan for the migration?

**Comment by smlambert** [comment]
re: https://github.com/adoptium/adoptium/issues/73#issuecomment-965684753 the PMC will be revisiting this decision in next week's meeting based on all of the community feedback surrounding it.

**Comment by racevedoo** [comment]
> re: [#73 (comment)](https://github.com/adoptium/adoptium/issues/73#issuecomment-965684753) the PMC will be revisiting this decision in next week's meeting based on all of the community feedback surrounding it.

any news regarding the jre decision? @smlambert

**Comment by smlambert** [comment]
re: https://github.com/adoptium/adoptium/issues/73#issuecomment-995756968 We have published them yesterday, https://github.com/adoptium/temurin17-binaries/releases/tag/jdk-17.0.1%2B12... blog post will be drafted to more broadly announce, but you should be able to pick them up via API / website shortly.

**Comment by dinvlad** [comment]
Thanks! Would it be possible to also publish this to the Docker Hub? Without those, not sure how many folks would actually benefit from it.. And for example, we consume Temurin just by building on top of its "blessed" base images, so pulling from another source is not an option in that case, unfortunately.

**Comment by karianna** [comment]
@gdams have the JRE based docker images been uploaded to DockerHub?

**Comment by sideeffffect** [comment]
For example [`eclipse-temurin:17.0.1_12-jre`](https://hub.docker.com/layers/eclipse-temurin/library/eclipse-temurin/17.0.1_12-jre/images/sha256-7b169d386822bd09fe00f18a5ea7bcc7e070bb7fdd15ab061acf98c33fad6a94?context=explore)

**Comment by smlambert** [comment]
Am closing this issue as we are tracking AIX jdk17 release blocker elsewhere (in a Temurin-compliance repo).
