### ISSUE TITLE
Checklist for Temurin Releases: 8u312-b08, jdk-11.0.13, and jdk-17.0.1

### ISSUE THREAD

**Issue by sxa** [adoptium/adoptium#83]
This Temurin release checklist based on the [release doc](https://github.com/adoptium/temurin-build/blob/master/RELEASING.md) captures what activities must happen during a release.

The target release date is: 22nd October 2021 (Primary platforms) 29th October 2021 (Other platforms)

The release champion for this release is: Stewart Addison @sxa 

Planned absences during the release cycle: None known so far

The role of the release champion is to ensure that all release activities listed in this checklist get completed (by delegation to the broader team or by the release champion themselves).  The final task of the release champion during a release is to confirm that all items in the checklist were completed satisfactorily and the release can be declared complete.

Everyone participating in a release, including the release champion are requested to provide feedback into the release retrospective so that the release process can be continuously improved (through simplification and/or automation).

-------

One Week Prior to Release:

- [x] **Release Champion named** whose responsibility is to ensure every item in this checklist gets completed
- [x] **Declare code freeze** to ensure stability of build systems and infrastructure during release process
- [x] **Disable nightly testing** to free up resources and ensure no competing jobs during release week [Draft PR to be merged on Tuesday](https://github.com/adoptium/ci-jenkins-pipelines/pull/209)
- [x] **Run a trial release pipeline** to ensure less surprises on release day (typically against a milestone build) [jdk8u](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/1824), [jdk11](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/1690/), [jdk17](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk17-pipeline/214/), (See potential blocker in comments)

-------

Release Week Checklist:

- [x] **Add website banner** (_automate_* via github workflow in website repository) - Announce that we target releases to be available within 48-72 hours of the GA tags being available [DRAFT PR](https://github.com/adoptium/adoptium.net/pull/215)
- [x] **Check Tags have been released upstream** - Look for mailing list announcements and `-ga` tags in version control.
- [x] **Check Tags have been Mirrored** [Mirrors](https://ci.adoptopenjdk.net/view/git-mirrors/job/git-mirrors/job/adoptium/). (Requires `move_to_next_tag` and the appropriate `-bNN` tag to be specified in the [jdk8u mercurial mirror job](https://ci.adoptopenjdk.net/view/git-mirrors/job/git-mirrors/job/adoptium/job/git-hg-jdk8u/))
- [x] **Launch build pipelines** for each version being released [(as per release doc](https://github.com/adoptium/temurin-build/blob/master/RELEASING.md#steps-for-every-version)) once release tags are available via [launch page](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/build) in Jenkins.  Provide links in this issue to each version's pipeline build(s). There may be multiple pipelines per version if primary and secondary platforms are separated to expedite the release.  In some cases,  where there are unforeseen configuration or infrastructure issues, reruns may be needed.
  - jdk8 pipeline(s): 
    -jdk8 pipeline: https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/1827/
      - rerun(s):
    - amr32 jdk8 pipeline:
      - reruns(s):
  - jdk11 pipeline(s):
    - jdk11 pipeline: https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/1698/
      - rerun(s): AIX due to build glitch: https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/1699/
  - jdk17 pipeline(s): https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk17-pipeline/218/
    - primary jdk17 pipeline:
      - rerun(s):
    - secondary jdk17 pipeline:
      - rerun(s):
- [x] **Add links to the [status doc](https://github.com/adoptium/adoptium/issues/81)** to indicate per-platform builds ready
- [x] **Summarize test results**.  Find each launched build pipeline in [TRSS](https://trss.adoptium.net/) to view a summary of test results.  Can use the Release Summary Report feature in TRSS to generate a summary of failures, history and possible issues in markup format to be added to this issue as a comment.
- [x] **Triage** each build and test failure in the release summary report (following the [Triage guidelines](https://github.com/adoptium/aqa-tests/blob/master/doc/Triage.md)) and determine blocking or non-blocking.  Supply links to triage issues or docs for each version here.
  - jdk8 triage summary: https://github.com/adoptium/adoptium/issues/88
  - jdk11 triage summary: https://github.com/adoptium/adoptium/issues/87
  - jdk17 triage summary: https://github.com/adoptium/adoptium/issues/89
- [x] **Fix** blocking failures if they exist and confirm others are non-blocking.
- [x] **Get PMC 'ready to publish' approval**, once no blocking failures exist.
- [x] **Publish the release** (run the restricted access [release tool job](https://ci.adoptopenjdk.net/job/build-scripts/job/release/job/refactor_openjdk_release_tool/) on Jenkins)
- [x] **Verify binaries published successfully** to github releases repo and website (_automate_*, this could also be an automated test)
- [x] **Update support page** (_automate_* github workflow to create a PR to update [support.handlebars](https://github.com/adoptium/adoptium.net/blob/master/src/handlebars/support.handlebars)) - [PR](https://github.com/adoptium/adoptium.net/pull/233)
- [x] **Update release notes** (_automate_* - github workflow to create update for [release notes page](https://adoptium.net/release_notes.html)) [PR](https://github.com/adoptium/adoptium.net/pull/235)
- [x] **Trigger linux installers pipeline** currently it is part of the build pipelines (will eventually be updated to run independently)
- [x] **Publicize the release** via Slack #release channel and Twitter (can be partially automated)
- [x] **Declare code freeze end** opening up the code for further development
- [x] **Remove website banner** (_automate_* via github workflow in website repository) [PR](https://github.com/adoptium/adoptium.net/pull/234)
- [x] **Check for presence of jdk8u aarch32 GA tag and mirror it** [Mercurial repo](https://hg.openjdk.java.net/aarch32-port/jdk8u) - [Mirror job](https://ci.adoptopenjdk.net/view/git-mirrors/job/git-mirrors/job/adoptium/job/git-hg-aarch32-jdk8u/)
- [x] **Do all of the above for the jdk8u/aarch32 build**
- [x] **Declare the release complete** and close this issue

**Comment by sxa** [comment]
POTENTIAL BLOCKER: JDK17u does not contain `_adopt` tags

**Comment by sxa** [comment]
I'm declaring this finalised now that the linux installers have gone out. We've also shipped JREs for 17. AIX JDK17 can be deferred to 17.0.2 if appropriate.
